services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogcms
      MYSQL_USER: blogcms
      MYSQL_PASSWORD: S@ng0905257554
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SERVER_MODE: "dev"
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: blogcms
      MYSQL_PASSWORD: S@ng0905257554
      MYSQL_DBNAME: blogcms
      MYSQL_MAX_IDLE_CONNS: 10
      MYSQL_MAX_OPEN_CONNS: 100
      MYSQL_CONN_MAX_LIFETIME: 3600
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DATABASE: 0
      LOG_LEVEL: "debug"
      FILE_LOG_NAME: "./storages/logs/dev.001.log"
      MAX_BACKUPS: 30
      MAX_AGE: 7
      MAX_SIZE: 1024
      COMPRESS: "true"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
