server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 3308
  username: blogcms
  password: S@ng0905257554
  dbname: blogcms
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true